<a href="https://colab.research.google.com/github/rehanmehdichandio/pandas-practice/blob/main/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Pandas</h1>

In [1]:
import numpy as np
import pandas as pd

**Series From List**

In [2]:
#Sting
country = ['Pakistan', 'India', 'USA','Nepal', 'Srilanka']

pd.Series(country)

0    Pakistan
1       India
2         USA
3       Nepal
4    Srilanka
dtype: object

In [3]:
#interger
runs = [13,14,58,90]

pd.Series(runs)

0    13
1    14
2    58
3    90
dtype: int64

In [4]:
#custom_index
marks = [76,89,19,33,70]
subjects = ['maths', 'English', 'JavScript', 'Physics', 'python']

pd.Series(marks , subjects)

maths        76
English      89
JavScript    19
Physics      33
python       70
dtype: int64

In [5]:
  result = pd.Series(marks , subjects, name='Rehan ke Marks')

In [ ]:
result

maths        76
English      89
JavScript    19
Physics      33
python       70
Name: Rehan ke Marks, dtype: int64

In [6]:
marks_dict = {
    'English' : 67,
    'Maths' : 78,
    'Physics' : 89
}

marks_dict_series = pd.Series(marks_dict, name = 'Rehan ki Marks')

In [7]:
marks_dict_series

English    67
Maths      78
Physics    89
Name: Rehan ki Marks, dtype: int64

**Series Attributes**

In [8]:
#Size
marks_dict_series.size

3

In [ ]:
#dtype
marks_dict_series.dtype

dtype('int64')

In [9]:
#name
marks_dict_series.name

'Rehan ki Marks'

In [10]:
#is_unique IF ALL UNIQUE RETURN TRUE ELSE RETURNS FALLS
marks_dict_series.is_unique

True

In [11]:
#index
marks_dict_series.index

Index(['English', 'Maths', 'Physics'], dtype='object')

In [ ]:
#value
marks_dict_series.values


array([67, 78, 89])

**Series Using read_csv**

In [18]:
# with one col
df = pd.read_csv('/content/subs.csv')
df

Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [17]:
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
vk

runs
match_no      
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [19]:
bol = pd.read_csv('/content/bollywood.csv', index_col='movie')

In [ ]:
bol

lead
movie                                                 
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

Series **Methods**



In [20]:
#head and tail
df.head()


Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [ ]:
vk.head(3)

runs
match_no      
1            1
2           23
3           13

In [ ]:
vk.tail(5)

runs
match_no      
211          0
212         20
213         73
214         25
215          7

In [21]:
#sample   randomly selected data
bol.sample(5)

lead
movie                                  
Jabariya Jodi         Sidharth Malhotra
Tulsi (film)            Manisha Koirala
Fever (2016 film)     Rajeev Khandelwal
Ek Hasina Thi (film)      Saif Ali Khan
Aisa Yeh Jahaan          Yashpal Sharma

In [ ]:
#value_counts --> movies
bol.value_counts()

lead            
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Kashmira Shah        1
Kartik Elangovan     1
Karisma Kapoor       1
Karan Sharma         1
Zulfi Sayed          1
Name: count, Length: 566, dtype: int64

In [22]:
#sort_values(by='parameter')
vk.sort_values(by='runs',ascending=False)

runs
match_no      
128        113
126        109
123        108
164        100
120        100
...        ...
93           0
211          0
130          0
8            0
135          0

[215 rows x 1 columns]

In [ ]:
vk.sort_values(by='runs', ascending=False).head(1).values

array([[113]])

In [ ]:
vk.sort_values(by='runs', ascending=False).head(1).values[0]

array([113])

In [ ]:
vk.sort_values(by='runs', inplace=True)

In [ ]:
vk

runs
match_no      
87           0
211          0
207          0
206          0
91           0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [ ]:
#sort_index --> inplace --> movies

bol.sort_index()

lead
movie                                       
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

 **Series Maths Maths Method**

In [23]:
#count
vk.count()

runs    215
dtype: int64

In [26]:
#sum --> product
vk.sum()

runs    6634
dtype: int64

In [27]:
vk.product()

runs    0
dtype: int64

In [37]:
#mean, mode, median, std, var
print(vk.mean())
print(vk.median())
print(bol.mode())
print(vk.std())
print(vk.var())

runs    30.855814
dtype: float64
runs    24.0
dtype: float64
           lead
0  Akshay Kumar
runs    26.229801
dtype: float64
runs    688.002478
dtype: float64


In [41]:
#min    #max
print(vk.min())
print(vk.max())

runs    0
dtype: int64
runs    113
dtype: int64


In [42]:
#describe
vk.describe()

runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000

In [44]:
df.describe()

Subscribers gained
count          365.000000
mean           135.643836
std             62.675023
min             33.000000
25%             88.000000
50%            123.000000
75%            177.000000
max            396.000000

**Series Indexing**

In [47]:
x = pd.Series([1,2,3,4,5,6,7,8,9])
x[1]  #negative indexing doesn't work

2

In [48]:
#slicing
vk[5:60]

runs
match_no      
6            9
7           34
8            0
9           21
10           3
11          10
12          38
13           3
14          11
15          50
16           2
17          22
18          19
19          16
20          15
21          20
22          38
23          19
24          24
25           7
26           2
27          16
28          17
29          24
30          38
31          34
32          42
33          13
34          58
35           3
36          14
37          37
38           9
39          23
40          12
41          71
42          35
43          30
44          56
45          67
46          27
47          27
48          39
49          15
50          11
51          31
52          70
53           8
54          35
55           8
56           6
57          57
58          22
59          16
60           4

In [49]:
#negative slicing
vk[-5:]

runs
match_no      
211          0
212         20
213         73
214         25
215          7

In [50]:
bol[-5:]

lead
movie                                   
Hum Tumhare Hain Sanam    Shah Rukh Khan
Aankhen (2002 film)     Amitabh Bachchan
Saathiya (film)             Vivek Oberoi
Company (film)                Ajay Devgn
Awara Paagal Deewana        Akshay Kumar

In [52]:
#fancy indexing
x[[1,3,4,5]]

1    2
3    4
4    5
5    6
dtype: int64

In [58]:
result

maths        76
English      89
JavScript    19
Physics      33
python       70
Name: Rehan ke Marks, dtype: int64

In [59]:
result['sst']=90

In [60]:
result

maths        76
English      89
JavScript    19
Physics      33
python       70
sst          90
Name: Rehan ke Marks, dtype: int64

In [61]:
#slicing
runs

[13, 14, 58, 90]

In [62]:
runs[1:3]=[100,100]

In [63]:
runs

[13, 100, 100, 90]

In [66]:
bol=['2 States (2014 Film)']= 'Alia Bhatt'
bol

SyntaxError: cannot assign to literal (<ipython-input-66-f8a6270b155b>, line 1)